# action.yml
name: "Codacy Coverage Reporter"
description: "Multi-language coverage reporter for Codacy"
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  project-token:
    description: 'Specify this project token'
    required: true
  args:
    description: 'Additional arguments for the script'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.project-token }}"
    - "${{ inputs.args }}"
