version: 2.1

orbs:
  codacy: codacy/base@5.2.3

workflows:
  version: 2
  tag_versions:
    jobs:
      - codacy/checkout_and_version
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          filters:
            branches:
              only:
                - master
          requires:
            - codacy/checkout_and_version
